name: AutoDoc Documentation

on:
  pull_request:
  workflow_dispatch:
    inputs:
      pr_number:
        description: "Pull Request number to approve"
        required: false

permissions:
  contents: write
  pull-requests: write

jobs:
  autodoc:
    uses: emaafe/autodoc/.github/workflows/autodoc.yml@main
    with:
      pr_number: ${{ github.event.inputs.pr_number || github.event.pull_request.number }}
    secrets:
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
